{{- if and (eq .Values.cache.provider "redis") (not .Values.cache.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seafile.redis.fullname" . }}
  labels:
    {{- include "seafile.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.cache.password | b64enc | quote }}
{{- end }}
