{{- if and .Values.cache.enabled (eq .Values.cache.provider "redis") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.redis.fullname" . }}
  labels: {{- include "seafile.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "seafile.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
