{{- if and .Values.database.enabled (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seafile.mariadb.fullname" . }}
  labels: {{- include "seafile.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.database.rootPassword | b64enc | quote }}
  mariadb-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
