{{- if eq (index .Values.ingress.annotations "kubernetes.io/spec.ingressClassName" | default "") "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "seafile.fullname" . }}-buffering
  namespace: {{ .Release.Namespace }}
spec:
  buffering:
    maxRequestBodyBytes: 0
    maxResponseBodyBytes: 0
    memRequestBodyBytes: 2097152
    memResponseBodyBytes: 2097152
{{- end }}
