{{- if and .Values.ingress.enabled .Values.ingress.traefik.buffering }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "seafile.fullname" . }}-buffering
  labels: {{- include "seafile.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: 0
    maxResponseBodyBytes: 0
    memRequestBodyBytes: 2097152
    memResponseBodyBytes: 2097152
{{- end }}
