apiVersion: v1
kind: Service
metadata:
  name: {{ include "seafile.fullname" . }}
  labels: {{- include "seafile.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.seafile.webdav.enabled }}
  - port: 8080
    targetPort: http-webdav
    protocol: TCP
    name: http-webdav
  {{- end }}
  selector:
    {{- include "seafile.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: seafile
